# Generated by Django 5.1 on 2024-09-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
