# Generated by Django 5.1 on 2024-09-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
    ]
