# Generated by Django 5.1 on 2025-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/profile/default-profile.png', upload_to='profile/', verbose_name='Image'),
        ),
    ]
