# Generated by Django 5.1 on 2025-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile/default-profile.jpg', upload_to='profile/', verbose_name='Image'),
        ),
    ]
