# Generated by Django 5.1 on 2024-09-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
