# Generated by Django 5.1 on 2024-09-06 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_employee'),
        ('user', '0003_alter_profile_name_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(choices=[('oral', 'oral'), ('vascular', 'vascular'), ('applicant', 'applicant')], max_length=30, verbose_name='Category')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offline_Patient',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('display_id', models.CharField(max_length=30, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.TextField(default='default', verbose_name='Address')),
                ('medical_history', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=190, null=True, verbose_name='Email')),
                ('profile_image', models.ImageField(default='profile/default-profile.png', upload_to='profile/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='street_address',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(default='default', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(default='default_address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=200, verbose_name='Speciality'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('machinary', models.CharField(blank=True, max_length=300, verbose_name='Machinary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('no_of_beds', models.IntegerField(default=0, verbose_name='No of Beds')),
                ('no_of_appointment', models.IntegerField(default=0, verbose_name='No of Appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd', to='opd.inventory')),
                ('offline_patients', models.ManyToManyField(related_name='opds', to='opd.offline_patient')),
                ('online_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_patient', to='user.profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd', to='opd.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
