# Generated by Django 5.1 on 2024-09-07 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0009_auto_20240907_1858'),
        ('user', '0004_auto_20240907_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Year of Experience'),
        ),
        migrations.AlterField(
            model_name='inventory_item',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='opd',
            name='no_of_appointment',
            field=models.PositiveIntegerField(default=0, verbose_name='No of Appointment'),
        ),
        migrations.AlterField(
            model_name='opd',
            name='no_of_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='No of Beds'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=10, verbose_name='Appointment ID')),
                ('date_of_appointment', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offline_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opd.offline_patient')),
                ('online_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='opd.opd')),
            ],
        ),
    ]
