# Generated by Django 5.1 on 2024-09-07 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0010_alter_doctor_experience_and_more'),
        ('user', '0004_auto_20240907_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=30, null=True, verbose_name='Appointment Type'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Appointment ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='offline_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_appoinments', to='opd.offline_patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='online_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_appointments', to='user.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('opd', 'appointment_id')},
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_type', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=30, null=True, verbose_name='Patient Type')),
                ('patient_id', models.CharField(max_length=10, null=True, verbose_name='Appointment ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offline_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_patients', to='opd.offline_patient')),
                ('online_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_patients', to='user.profile')),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='opd.opd')),
            ],
            options={
                'unique_together': {('opd', 'patient_id')},
            },
        ),
    ]
