# Generated by Django 5.1 on 2024-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0011_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bed_reservation',
            field=models.PositiveIntegerField(default=0, verbose_name='Bed Reservation Hour'),
        ),
        migrations.AddField(
            model_name='patient',
            name='billing_report',
            field=models.TextField(null=True, verbose_name='Bill Report'),
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateTimeField(null=True, verbose_name='Next Appointment Date'),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Bill'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Patient ID'),
        ),
    ]
