# Generated by Django 5.1 on 2024-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0012_patient_bed_reservation_patient_billing_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offline_patient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
