# Generated by Django 5.1 on 2024-09-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0013_offline_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='opd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.opd'),
        ),
    ]
