# Generated by Django 5.1 on 2024-09-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0014_alter_inventory_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('seen', 'seen'), ('not_seen', 'not_seen')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
