# Generated by Django 5.1 on 2024-09-10 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
