# Generated by Django 5.1 on 2024-09-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0021_alter_opd_no_of_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_item',
            name='machinery',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Appointment ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(max_length=30, verbose_name='Appointment Type'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='opd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.opd'),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='email',
            field=models.EmailField(max_length=190, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offline_patient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='opd',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(max_length=30, verbose_name='Patient Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Bill'),
        ),
        migrations.DeleteModel(
            name='Machinery',
        ),
    ]
