# Generated by Django 5.1 on 2024-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0022_remove_inventory_item_machinery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='no_of_appointment',
            field=models.IntegerField(default=0, verbose_name='No of Appointment'),
        ),
    ]
