# Generated by Django 5.1 on 2024-09-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0023_alter_opd_no_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='offline_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_appoinments', to='opd.offline_patient'),
        ),
    ]
