# Generated by Django 5.1 on 2024-09-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0024_alter_appointment_offline_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='no_of_appointment',
            field=models.PositiveIntegerField(default=0, verbose_name='No of Appointment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='offline_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_patients', to='opd.offline_patient'),
        ),
    ]
