# Generated by Django 5.1 on 2024-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0025_alter_opd_no_of_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_item',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
