# Generated by Django 5.1 on 2024-09-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0026_alter_inventory_item_price'),
        ('user', '0008_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='offline_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_appoinment', to='opd.offline_patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='online_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_appointment', to='user.profile'),
        ),
    ]
