# Generated by Django 5.1 on 2024-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0027_alter_appointment_offline_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_of_appointment',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
