# Generated by Django 5.1 on 2024-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0029_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date'),
        ),
    ]
