# Generated by Django 5.1 on 2024-09-28 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0030_alter_appointment_appointment_date'),
        ('user', '0015_profile_blood_group_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='offline_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_appoinment', to='opd.offline_patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='offline_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_patients', to='opd.offline_patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='online_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_patients', to='user.profile'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='opd.inventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.DeleteModel(
            name='Inventory_Item',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
