# Generated by Django 5.1 on 2024-10-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0031_alter_appointment_offline_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='offline_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_appoinment', to='opd.offline_patient'),
        ),
    ]
